### ISSUE TITLE
Only showing 2 red tests

### ISSUE THREAD

**Issue by jtrott** [daduke/Xymondash#1]
Looks like a great new interface option for xymon.
I've set it up and can confirm I'm getting JSON with 360 odd items in it, but the interface is only showing the first 2 red tests.
Checking the console in Firefox shows the following error:

Error: Syntax error, unrecognized expression: [data-host=host.domain.local]     
jquery.js:2:12961

Let me know if you need me to capture any more information to assist debugging.

**Comment by daduke** [comment]
thanks for your feedback! I'm currently reworking the code because I noticed a problem that doesn't occur in our setup, but your problem seems to be unrelated. Could you send me your JSON file? Then I can debug locally.

**Comment by jtrott** [comment]
Sent via email.

**Comment by jtrott** [comment]
Good stuff, it now tries to show all the problems.
It then pops up a box stating:
Your setting yielded too many tests! Please choose fewer colors or prios.

OK, I'll work on that. I thought perhaps I might be able to Mark all as seen, but that doesn't do anything and the Firefox console shows:

Error: too many results          main.js:341:35

It would be nice if we could exclude certain columns from the display, that would cut our listing down considerably.

Also, I have set in the settings to uncheck prio1 through prio3 in priorities and background but they still show up on the page?

**Comment by daduke** [comment]
glad to hear we're making progress.

I'm not sure I understand tho. You say "would be nice if we could exclude certain columns" vs "uncheck prio1 through prio3" - that's the same thing! As soon as you uncheck a prio in the settings, it won't be displayed.

The 200 events limit is an arbitrary number in 339 in js/main.js, you can increase it if you want, but the result won't be pretty...

**Comment by jtrott** [comment]
Exclude certain columns like disk, cpu, memory, that sort of thing.
I assumed that unchecking prio1 would remove it from the display but my screen shot tells a different tale...

<img width="1252" alt="screen shot 2018-06-29 at 17 20 03" src="https://user-images.githubusercontent.com/1151853/42078750-0417870e-7bc1-11e8-9ad7-a61a43e13804.png">

I'll have a play with adjusting the limit and see how I go ;)

**Comment by jtrott** [comment]
Interesting.... adjusting the limit from 200 to 400 removed the error and also hides the prio1, prio2, and prio3 columns.

**Comment by daduke** [comment]
excluding individual tests can be done by modifiying the URL parameter which will be passed on to `xymon2json`. For example, appending `?test=[^disk]` should exclude the disk test.

The whole point of the project is to show the (hopefully) few non-green tests in your xymon, so I was a bit astonished by your JSON breaking the 200 limit....

**Comment by jtrott** [comment]
Yep, working on getting that number down and your dashboard will hopefully help with that.
I'm hoping your output will be easier to get on top of than the all non-green or all red pages.

Just tested excluding a colun and it looks like the xymon2json script ignores the first set of parameters.
If I manually run xymon2json?test=[^disk] I get a JSON with less than 200 results.
When the page is loaded it runs this:

xymon2json?test=[^disk]?color=red,purple,yellow,blue

Which returns the over 200 results with the disk column included.

**Comment by daduke** [comment]
I'll look into it

**Comment by daduke** [comment]
fixed by 09e1d4c48af7492cb9e35573fd43a0696c1d6173

**Comment by jtrott** [comment]
Sorry, just tested and still not filtering out columns.

**Comment by daduke** [comment]
Can you send a screenshot?

**Comment by daduke** [comment]
solved via email
