### ISSUE TITLE
xymondash on ubuntu 24.04

### ISSUE THREAD

**Issue by pretocj2** [daduke/Xymondash#10]
Hi

Im sure im doing something wrong and not sure where to start.

On the server: Ubuntu 24.04  (Azure VM)
xymon          4.3.30-1build2
apache2        2.4.58-1ubuntu8.4

Checked out xymondash and did the configs, all looks ok

When opening xymondash in dev mode in chrome I get the following:
2 x Incorrect use of <label for=FORM_ELEMENT>
    <label for="duration">Duration</label>  and
    <label for="ackmsg">Message</label>

2 x Trusted type expected, but String received  =in jquery.js

This document requires 'TrustedHTML' assignment.
Uncaught TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.

    r.appendChild(e).innerHTML = "<a id='" + S + "' href='' disabled='disabled'></a><select id='" + S + "-\r\\' disabled='disabled'><option selected=''></option></select>",     and
   xe.innerHTML = "<textarea>x</textarea>",

Best regards

**Comment by pretocj2** [comment]
Good morning

removing the following line from apache2 config allows xymondash to load.

Header always set Content-Security-Policy "object-src 'none'; base-uri 'none'; require-trusted-types-for 'script'; frame-ancestors 'self';"

best regards

**Comment by daduke** [comment]
hey,

sorry for the late reply, just came back from vacation. Glad you found it, I don't think I would have had a chance to debug this remotely...
Do you know where this apache config came from?

cheers,
-Christian

**Comment by pretocj2** [comment]
Hi Christian

The headers were added in our apache config to harden apache2.

I misplaced the guide I followed that recommended those entries to be added. 
Will update here when I manage to find it again. 

SSLabs still give me an A+ with the Content-Security-Policy entries commented.
https://securityheaders.com/ test not so good :-(

Here's all of them I commented:
Header set X-Content-Type-Options: "nosniff"
Header always set Content-Security-Policy "object-src 'none'; base-uri 'none'; require-trusted-types-for 'script'; frame-ancestors 'self';"
Header set Content-Security-Policy "frame-ancestors 'self';"
Header always set Strict-Transport-Security "max-age=31536000; includeSubdomains; preload"

PS. xymondash is great, thank you so much for the effort you guys have put into this project.

I would like to make one or two feature requests if possible. 

Best regards

Chris

**Comment by pretocj2** [comment]
Hi

Here's the guide I followed:  https://beguier.eu/nicolas/articles/apache-tls-security-configuration.html

Best regards

Chris

**Comment by daduke** [comment]
thanks, I'll look into this in the near future. 

can't make any promises about those feature requests - first I'll have to reverse engineer my 6 y.o code :smile: 

-d

**Comment by daduke** [comment]
the problem is the `require-trusted-types-for 'script';` - we need to be able to edit the DOM. `Content-Security-Policy "object-src 'none'; base-uri 'none';  frame-ancestors 'self';"` is working fine.

**Comment by pretocj2** [comment]
Hi

Apologies for only responding now. I made the change you suggested in apache2 and all is good. Thank you so much.

All suggested security headers configured and now get an A+ score.

**Comment by daduke** [comment]
glad it worked out for you!
