### ISSUE TITLE
Path to python executable as config.ini variable

### ISSUE THREAD

**Issue by jtrott** [daduke/Xymondash#2]
Would be good to add the path to the Python executable to the config.ini file.
On my CentOS 7 systems its python36 rather than python3.

**Comment by daduke** [comment]
and there's no python3 symlink? The `#!/usr/bin/env python3` shebang is the accepted way and I'm a bit hesitant to clutter the config file with stuff that's unnecessary for 98% of users..

**Comment by jtrott** [comment]
If you are using CentOS 7 and you install the Python 3.6 rpm package from epel, you will get a /usr/bin/python36 file but no symlink from /usr/bin/python3.
I'm just trying to make my life easier for when you update the code ;)

**Comment by daduke** [comment]
I know and you have a point, but it's a bit of a special case..  git pull
