### ISSUE TITLE
Use pagepath cookie to limit scope of dashboard

### ISSUE THREAD

**Issue by jtrott** [daduke/Xymondash#3]
I've done a bit of hacking of the main.js file to use the pagepath cookie to filter the json output to just show the hosts from the page that was selected before the dashboard was opened.
I'm not sure if that is the best way to get this functionality or not.

**Comment by daduke** [comment]
got some code?

**Comment by jtrott** [comment]
[diff.txt](https://github.com/daduke/Xymondash/files/2187175/diff.txt)

**Comment by daduke** [comment]
what's wrong with just using `xymondashdev/?page=san` in the URL? This allows you to have multiple browser windows with different xymon pages..

**Comment by jtrott** [comment]
OK, that takes care of the one off case where we need a bookmark to a page dashboard. I can simplify my hack code a bit!
Mostly we want to load the dashboard that represents where we are in the xymon page layout.
Switching into dashboard view mode if you like.

**Comment by daduke** [comment]
I'm afraid I don't understand what you're trying to accomplish.

**Comment by jtrott** [comment]
OK, that takes care of the one off case where we need a bookmark to a page dashboard. I can simplify my hack code a bit!
We have a 2 level hierarchy for pages. First level is engineers, second level is clients. It's a much nicer view for an engineer of all their client issues in the dashboard, and it's super simple to open the correct dashboard from the view menu in xymon if it takes them straight to the relevant dashboard.
No worries if you don't want to add an option for this, I can keep adding my hack to your code whenever I check out a new copy.

**Comment by daduke** [comment]
if I understood your use case and there was a chance it's generally useful I'd be happy to include it, but config[] is called config for a reason and IMHO shouldn't hold hardcoded values.
so: I'll be AFK for the next two weeks anyway, but after that I'd be happy to take a look at your cleaned-up patch and see if it fits in, deal?

**Comment by jtrott** [comment]
Sounds good, enjoy your break.

**Comment by daduke** [comment]
I read this thread and your patch again and I still don't get it. You'd like to display a specific xymon page? You can do that by appending `?page=foo` to the URL. Why save it in the config cookie? It's not a config option.

**Comment by jtrott** [comment]
The idea is to dynamically show a dashboard that relates just to the page that is currently being viewed in xymon.
Click on the dashboard link, get taken to the dashboard view for the page you are on, or the page the host is on.
Click on the dashboard link when not viewing a page and get taken to the main dashboard view.
I could maybe use javascript to dynamically change the menu item link, but this seemed easier.

**Comment by daduke** [comment]
ok finally I understand what you're trying to do. Now: where does this 'dashboard link' come from? Can't you append the page there? I'm asking because hard redirecting to a specific page whenever pagepath is present might be what you want, but not necessarily what everybody else wants, so I'm somewhat hesitant to include that as a default.

**Comment by jtrott** [comment]
From /etc/xymon/xmonmenu.cfg:

<div id="menue">
    <div class="outer">
      <span class="menutag"><a href="javascript:;">Views</a><span class="invis">: </span></span>
	<a class="inner-1" href="$XYMONSERVERWWWURL/xymon.html">Main view</a><span class="invis"> | </span>
	<a class="inner" href="$XYMONSERVERWWWURL/nongreen.html">All non-green view</a><span class="invis"> | </span>
	<a class="inner" href="$XYMONSERVERWWWURL/red.html">All red view</a><span class="invis"> | </span>
	<a class="inner" href="$XYMONSERVERCGIURL/criticalview.sh">Critical systems</a>
	<a class="inner" href="$XYMONSERVERWWWURL/xymondash/">Xymon Dashboard</a>
    </div>

I wouldn't want it to be a default, I'm sure it's aberrant behaviour, it's just how we like to work.

**Comment by jtrott** [comment]
Well, that didn't go how I thought it would...

```
<div id="menue">
    <div class="outer">
      <span class="menutag"><a href="javascript:;">Views</a><span class="invis">: </span></span>
	<a class="inner-1" href="$XYMONSERVERWWWURL/xymon.html">Main view</a><span class="invis"> | </span>
	<a class="inner" href="$XYMONSERVERWWWURL/nongreen.html">All non-green view</a><span class="invis"> | </span>
	<a class="inner" href="$XYMONSERVERWWWURL/red.html">All red view</a><span class="invis"> | </span>
	<a class="inner" href="$XYMONSERVERCGIURL/criticalview.sh">Critical systems</a>
	<a class="inner" href="$XYMONSERVERWWWURL/xymondash/">Xymon Dashboard</a>
    </div>

```

**Comment by daduke** [comment]
I see. You only have a generic URL for all xymon pages. I still think including the patch would cause unexpected behavior for too many innocent bystanders. Would you be ok with applying the patch locally? The good news is that I don't foresee any major code changes anytime soon.
