### ISSUE TITLE
Disable test does not work for FQDN hosts

### ISSUE THREAD

**Issue by john-d-alexander** [daduke/Xymondash#4]
Disabling of tests with FQDN hosts generates a 400 error.  This appears to be fixed by replacing the following line in xymon-disable:

allowed_chars = re.compile(r'^[a-zA-Z0-9\-,\[\]\^\|\'? ]+$')

with the following line from xymon-ack (this was fixed by Christian yesterday)

allowed_chars = re.compile(r'^[a-zA-Z0-9\.\-,\[\]\^\|\'? ]+$')

**Comment by daduke** [comment]
fixed by 918fc85f8fa5ce5b4c97a18ad70c224b1faaaa68
